version: "3.8"

services:

  # ----------------------------------------- RABBIT-MQ ----------------------------------------------------------------
  rabbit-mq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
  # --------------------------------------- API-GATEWAY ----------------------------------------------------------------

  api-gateway-nginx:
    image: ghcr.io/tobias-pe/api-gateway-nginx:latest
    build:
      dockerfile: docker/nginx/api-gateway/Dockerfile
    ports:
      - "80:50000"
    env_file:
      - ./config/docker.env
    depends_on:
      - api-gateway

  api-gateway:
    image: ghcr.io/tobias-pe/api-gateway:latest
    build:
      dockerfile: ./services/api-gateway/Dockerfile
    env_file:
      - ./config/docker.env
    depends_on:
      - currency-nginx
      - stock-nginx
      - cart-nginx
      - order-nginx
      - rabbit-mq

  # ---------------------------------------- CURRENCY ------------------------------------------------------------------

  currency-nginx:
    image: ghcr.io/tobias-pe/currency-nginx:latest
    build:
      dockerfile: docker/nginx/currency/Dockerfile
    env_file:
      - ./config/docker.env
    depends_on:
      - currency

  currency:
    image: ghcr.io/tobias-pe/currency:latest
    build:
      dockerfile: ./services/currency/Dockerfile
    env_file:
      - ./config/docker.env

  # ------------------------------------------- STOCK ------------------------------------------------------------------

  stock-nginx:
    image: ghcr.io/tobias-pe/stock-nginx:latest
    build:
      dockerfile: docker/nginx/stock/Dockerfile
    env_file:
      - ./config/docker.env
    depends_on:
      - stock

  stock:
    image: ghcr.io/tobias-pe/stock:latest
    build:
      dockerfile: ./services/stock/Dockerfile
    env_file:
      - ./config/docker.env
    depends_on:
      - stock-mongodb
      - mongo_seed
      - rabbit-mq

  stock-mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"

  mongo_seed:
    image: ghcr.io/tobias-pe/mongo-seed:latest
    build:
      dockerfile: docker/mongo/Dockerfile
    depends_on:
      - stock-mongodb

  # -------------------------------------------- CART ------------------------------------------------------------------

  cart-nginx:
    image: ghcr.io/tobias-pe/cart-nginx:latest
    build:
      dockerfile: docker/nginx/cart/Dockerfile
    env_file:
      - ./config/docker.env
    depends_on:
      - cart

  cart:
    image: ghcr.io/tobias-pe/cart:latest
    build:
      dockerfile: ./services/cart/Dockerfile
    env_file:
      - ./config/docker.env
    depends_on:
      - cart-redis
      - rabbit-mq

  cart-redis:
    image: "redis:6"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"

  # ------------------------------------------- ORDER ------------------------------------------------------------------

  order-nginx:
    image: ghcr.io/tobias-pe/order-nginx:latest
    build:
      dockerfile: docker/nginx/order/Dockerfile
    env_file:
      - ./config/docker.env
    depends_on:
      - order

  order:
    image: ghcr.io/tobias-pe/order:latest
    build:
      dockerfile: ./services/order/Dockerfile
    env_file:
      - ./config/docker.env
    depends_on:
      - order-mongodb
      - rabbit-mq

  order-mongodb:
    image: mongo:4.4
    ports:
      - "27018:27017"

  # ------------------------------------------- PAYMENT ----------------------------------------------------------------

  payment:
    image: ghcr.io/tobias-pe/payment:latest
    build:
      dockerfile: ./services/payment/Dockerfile
    env_file:
      - ./config/docker.env
    depends_on:
      - rabbit-mq

  # ------------------------------------------- SHIPMENT ---------------------------------------------------------------

  shipment:
    image: ghcr.io/tobias-pe/shipment:latest
    build:
      dockerfile: ./services/shipment/Dockerfile
    env_file:
      - ./config/docker.env
    depends_on:
      - rabbit-mq

  # ------------------------------------------- E-Mail ---------------------------------------------------------------

  e-mail:
    image: ghcr.io/tobias-pe/email:latest
    build:
      dockerfile: ./services/email/Dockerfile
    env_file:
      - ./config/docker.env
    depends_on:
      - rabbit-mq

  # ------------------------------------------- E-Mail ---------------------------------------------------------------

  supplier:
    image: ghcr.io/tobias-pe/supplier:latest
    build:
      dockerfile: ./services/supplier/Dockerfile
    env_file:
      - ./config/docker.env
    depends_on:
      - rabbit-mq


    # ------------------------------------------- MONITORING -----------------------------------------------------------
  prometheus:
    image: prom/prometheus:v2.31.2
    ports:
      - "9000:9090"
    volumes:
      - ./config:/etc/prometheus
      - prometheus_data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml

  node-exporter:
    image: stefanprodan/swarmprom-node-exporter:v0.16.0
    command:
      - '--path.sysfs=/host/sys'
      - '--path.procfs=/host/proc'
      - '--collector.textfile.directory=/etc/node-exporter/'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
      - '--no-collector.ipvs'
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /etc/hostname:/etc/nodename
    ports:
      - "9100:9100"
    environment:
      - NODE_ID={{.Node.ID}}

  dockerd-exporter:
    image: stefanprodan/caddy
    environment:
      - DOCKER_GWBRIDGE_IP=172.18.0.1
    configs:
      - source: ./config/dockerd/Caddyfile
        target: /etc/caddy/Caddyfile

  cadvisor:
    image: google/cadvisor
    command: -logtostderr -docker_only
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/rootfs:ro
      - /var/run:/var/run
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "9200:8080"

  grafana:
    image: grafana/grafana:8.2.6
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./config/grafana/dashboards:/etc/grafana/provisioning/dashboards/
      - ./config/grafana/dashboards:/etc/grafana/dashboards/

volumes:
  prometheus_data: { }
  grafana_data: { }