version: "3.9"

#  interesting for docker swarm:
#  deploy:
#    mode: replicated
#    replicas: 2
#    endpoint_mode: dnsrr
#    placement:
#      max_replicas_per_node: 4
#    resources:
#      limits:
#        cpus: '0.50'
#        memory: 50M
#      reservations:
#        cpus: '0.25'
#        memory: 20M
#    restart_policy:
#      condition: on-failure
#      delay: 5s
#      max_attempts: 3
#      window: 30s

services:

  # ----------------------------------------- RABBIT-MQ ----------------------------------------------------------------
  rabbit-mq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
  # --------------------------------------- API-GATEWAY ----------------------------------------------------------------

  api-gateway-nginx:
    image: ghcr.io/tobias-pe/api-gateway-nginx:latest
    build:
      dockerfile: build/nginx/api-gateway/Dockerfile
    ports:
      - "80:50000"
    env_file:
      - ./config/docker.env
    depends_on:
      - api-gateway

  api-gateway:
    image: ghcr.io/tobias-pe/api-gateway:latest
    build:
      dockerfile: ./services/api-gateway/Dockerfile
    env_file:
      - ./config/docker.env
    depends_on:
      - currency-nginx
      - stock-nginx
      - cart-nginx
      - order-nginx

  # ---------------------------------------- CURRENCY ------------------------------------------------------------------

  currency-nginx:
    image: ghcr.io/tobias-pe/currency-nginx:latest
    build:
      dockerfile: build/nginx/currency/Dockerfile
    env_file:
      - ./config/docker.env
    depends_on:
      - currency

  currency:
    image: ghcr.io/tobias-pe/currency:latest
    build:
      dockerfile: ./services/currency/Dockerfile
    env_file:
      - ./config/docker.env

  # ------------------------------------------- STOCK ------------------------------------------------------------------

  stock-nginx:
    image: ghcr.io/tobias-pe/stock-nginx:latest
    pull_policy: always
    build:
      dockerfile: build/nginx/stock/Dockerfile
    env_file:
      - ./config/docker.env
    depends_on:
      - stock

  stock:
    image: ghcr.io/tobias-pe/stock:latest
    pull_policy: always
    build:
      dockerfile: ./services/stock/Dockerfile
    env_file:
      - ./config/docker.env
    depends_on:
      - stock-mongodb
      - mongo_seed

  stock-mongodb:
    image: mongo:5
    ports:
      - "27017:27017"

  mongo_seed:
    image: ghcr.io/tobias-pe/mongo-seed:latest
    pull_policy: always
    build:
      dockerfile: ./build/mongo/Dockerfile
    depends_on:
      - stock-mongodb

  # -------------------------------------------- CART ------------------------------------------------------------------

  cart-nginx:
    image: ghcr.io/tobias-pe/cart-nginx:latest
    pull_policy: always
    build:
      dockerfile: build/nginx/cart/Dockerfile
    env_file:
      - ./config/docker.env
    depends_on:
      - cart

  cart:
    image: ghcr.io/tobias-pe/cart:latest
    pull_policy: always
    build:
      dockerfile: ./services/cart/Dockerfile
    env_file:
      - ./config/docker.env
    depends_on:
      - cart-redis

  cart-redis:
    image: "redis:6"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"

  # ------------------------------------------- ORDER ------------------------------------------------------------------

  order-nginx:
    image: ghcr.io/tobias-pe/order-nginx:latest
    pull_policy: always
    build:
      dockerfile: build/nginx/order/Dockerfile
    env_file:
      - ./config/docker.env
    depends_on:
      - order

  order:
    image: ghcr.io/tobias-pe/order:latest
    pull_policy: always
    build:
      dockerfile: ./services/order/Dockerfile
    env_file:
      - ./config/docker.env
    depends_on:
      - order-mongodb

  order-mongodb:
    image: mongo:5
    ports:
      - "27018:27017"