version: "3.8"

#  interesting for docker swarm:
#  deploy:
#    mode: replicated
#    replicas: 2
#    endpoint_mode: dnsrr
#    placement:
#      max_replicas_per_node: 4
#    resources:
#      limits:
#        cpus: '0.50'
#        memory: 50M
#      reservations:
#        cpus: '0.25'
#        memory: 20M
#    restart_policy:
#      condition: on-failure
#      delay: 5s
#      max_attempts: 3
#      window: 30s

services:

  # ----------------------------------------- RABBIT-MQ ----------------------------------------------------------------
  rabbit-mq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
  # --------------------------------------- API-GATEWAY ----------------------------------------------------------------

  api-gateway-nginx:
    image: ghcr.io/tobias-pe/api-gateway-nginx:latest
    ports:
      - "80:50000"
    env_file:
      - ./config/docker.env
    depends_on:
      - api-gateway

  api-gateway:
    image: ghcr.io/tobias-pe/api-gateway:latest
    env_file:
      - ./config/docker.env
    depends_on:
      - currency-nginx
      - stock-nginx
      - cart-nginx
      - order-nginx
      - rabbit-mq

  # ---------------------------------------- CURRENCY ------------------------------------------------------------------

  currency-nginx:
    image: ghcr.io/tobias-pe/currency-nginx:latest
    env_file:
      - ./config/docker.env
    depends_on:
      - currency

  currency:
    image: ghcr.io/tobias-pe/currency:latest
    env_file:
      - ./config/docker.env

  # ------------------------------------------- STOCK ------------------------------------------------------------------

  stock-nginx:
    image: ghcr.io/tobias-pe/stock-nginx:latest
    env_file:
      - ./config/docker.env
    depends_on:
      - stock

  stock:
    image: ghcr.io/tobias-pe/stock:latest
    env_file:
      - ./config/docker.env
    depends_on:
      - stock-mongodb
      - mongo_seed
      - rabbit-mq

  stock-mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"

  mongo_seed:
    image: ghcr.io/tobias-pe/mongo-seed:latest
    depends_on:
      - stock-mongodb

  # -------------------------------------------- CART ------------------------------------------------------------------

  cart-nginx:
    image: ghcr.io/tobias-pe/cart-nginx:latest
    env_file:
      - ./config/docker.env
    depends_on:
      - cart

  cart:
    image: ghcr.io/tobias-pe/cart:latest
    env_file:
      - ./config/docker.env
    depends_on:
      - cart-redis
      - rabbit-mq

  cart-redis:
    image: "redis:6"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"

  # ------------------------------------------- ORDER ------------------------------------------------------------------

  order-nginx:
    image: ghcr.io/tobias-pe/order-nginx:latest
    env_file:
      - ./config/docker.env
    depends_on:
      - order

  order:
    image: ghcr.io/tobias-pe/order:latest
    env_file:
      - ./config/docker.env
    depends_on:
      - order-mongodb
      - rabbit-mq

  order-mongodb:
    image: mongo:4.4
    ports:
      - "27018:27017"

  # ------------------------------------------- PAYMENT ----------------------------------------------------------------

  payment:
    image: ghcr.io/tobias-pe/payment:latest
    env_file:
      - ./config/docker.env
    depends_on:
      - rabbit-mq

  # ------------------------------------------- SHIPMENT ---------------------------------------------------------------

  shipment:
    image: ghcr.io/tobias-pe/shipment:latest
    env_file:
      - ./config/docker.env
    depends_on:
      - rabbit-mq

  # ------------------------------------------- E-Mail ---------------------------------------------------------------

  e-mail:
    image: ghcr.io/tobias-pe/email:latest
    env_file:
      - ./config/docker.env
    depends_on:
      - rabbit-mq

  # ------------------------------------------- E-Mail ---------------------------------------------------------------

  supplier:
    image: ghcr.io/tobias-pe/supplier:latest
    env_file:
      - ./config/docker.env
    depends_on:
      - rabbit-mq