version: "3.8"

services:

  # ----------------------------------------- RABBIT-MQ ----------------------------------------------------------------
  rabbit-mq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10
        delay: 5s
        window: 30s
  # --------------------------------------- API-GATEWAY ----------------------------------------------------------------

  api-gateway-nginx:
    image: ghcr.io/tobias-pe/api-gateway-nginx:latest
    ports:
      - "80:50000"
    env_file:
      - ./config/docker.env
    depends_on:
      - api-gateway
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10
        delay: 5s
        window: 30s

  api-gateway:
    image: ghcr.io/tobias-pe/api-gateway:latest
    env_file:
      - ./config/docker.env
    environment:
      - SERVICE_NAME=api-gateway
    depends_on:
      - currency-nginx
      - stock-nginx
      - cart-nginx
      - order-nginx
      - rabbit-mq
    deploy:
      mode: replicated
      replicas: 8
      placement:
        max_replicas_per_node: 4
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
      restart_policy:
        delay: 5s
        window: 30s

  # ---------------------------------------- CURRENCY ------------------------------------------------------------------

  currency-nginx:
    image: ghcr.io/tobias-pe/currency-nginx:latest
    env_file:
      - ./config/docker.env
    depends_on:
      - currency
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10
        delay: 5s
        window: 30s

  currency:
    image: ghcr.io/tobias-pe/currency:latest
    env_file:
      - ./config/docker.env
    environment:
      - SERVICE_NAME=currency
    deploy:
      mode: replicated
      replicas: 4
      placement:
        max_replicas_per_node: 4
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
      restart_policy:
        delay: 5s
        window: 30s

  # ------------------------------------------- STOCK ------------------------------------------------------------------

  stock-nginx:
    image: ghcr.io/tobias-pe/stock-nginx:latest
    env_file:
      - ./config/docker.env
    depends_on:
      - stock
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10
        delay: 5s
        window: 30s

  stock:
    image: ghcr.io/tobias-pe/stock:latest
    env_file:
      - ./config/docker.env
    environment:
      - SERVICE_NAME=stock
    depends_on:
      - stock-mongodb
      - mongo_seed
      - rabbit-mq
    deploy:
      mode: replicated
      replicas: 8
      placement:
        max_replicas_per_node: 4
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
      restart_policy:
        delay: 5s
        window: 30s

  stock-mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    environment:
      - MONGO_REPLICA_SET_NAME=stockDB0
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo --quiet) -eq 1
      interval: 10s
      start_period: 30s
    command: [ "--replSet", "stockDB0", "--bind_ip_all" ]
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10
        delay: 5s
        window: 30s

  mongo_seed:
    image: ghcr.io/tobias-pe/mongo-seed:latest
    depends_on:
      - stock-mongodb
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10
        delay: 5s
        window: 30s

  # -------------------------------------------- CART ------------------------------------------------------------------

  cart-nginx:
    image: ghcr.io/tobias-pe/cart-nginx:latest
    env_file:
      - ./config/docker.env
    depends_on:
      - cart
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10
        delay: 5s
        window: 30s

  cart:
    image: ghcr.io/tobias-pe/cart:latest
    env_file:
      - ./config/docker.env
    environment:
      - SERVICE_NAME=cart
    depends_on:
      - cart-redis
      - rabbit-mq
    deploy:
      mode: replicated
      replicas: 4
      placement:
        max_replicas_per_node: 4
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
      restart_policy:
        delay: 5s
        window: 30s

  cart-redis:
    image: "redis:6"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
#    ports:
#      - "6379:6379"
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10
        delay: 5s
        window: 30s

  # ------------------------------------------- ORDER ------------------------------------------------------------------

  order-nginx:
    image: ghcr.io/tobias-pe/order-nginx:latest
    env_file:
      - ./config/docker.env
    depends_on:
      - order
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10
        delay: 5s
        window: 30s

  order:
    image: ghcr.io/tobias-pe/order:latest
    env_file:
      - ./config/docker.env
    environment:
      - SERVICE_NAME=order
    depends_on:
      - order-mongodb
      - rabbit-mq
    deploy:
      mode: replicated
      replicas: 6
      placement:
        max_replicas_per_node: 4
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
      restart_policy:
        delay: 5s
        window: 30s

  order-mongodb:
    image: mongo:4.4
    ports:
      - "27018:27017"
    environment:
      - MONGO_REPLICA_SET_NAME=orderDB0
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo --quiet) -eq 1
      interval: 10s
      start_period: 30s
    command: [ "--replSet", "orderDB0", "--bind_ip_all" ]
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10
        delay: 5s
        window: 30s

  # ------------------------------------------- PAYMENT ----------------------------------------------------------------

  payment:
    image: ghcr.io/tobias-pe/payment:latest
    env_file:
      - ./config/docker.env
    environment:
      - SERVICE_NAME=payment
    depends_on:
      - rabbit-mq
    deploy:
      mode: replicated
      replicas: 4
      placement:
        max_replicas_per_node: 4
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
      restart_policy:
        delay: 5s
        window: 30s

  # ------------------------------------------- SHIPMENT ---------------------------------------------------------------

  shipment:
    image: ghcr.io/tobias-pe/shipment:latest
    env_file:
      - ./config/docker.env
    environment:
      - SERVICE_NAME=shipment
    depends_on:
      - rabbit-mq
    deploy:
      mode: replicated
      replicas: 4
      placement:
        max_replicas_per_node: 4
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
      restart_policy:
        delay: 5s
        window: 30s

  # --------------------------------------------- E-Mail ---------------------------------------------------------------

  e-mail:
    image: ghcr.io/tobias-pe/email:latest
    env_file:
      - ./config/docker.env
    environment:
      - SERVICE_NAME=e-mail
    depends_on:
      - rabbit-mq
    deploy:
      mode: replicated
      replicas: 4
      placement:
        max_replicas_per_node: 4
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
      restart_policy:
        delay: 5s
        window: 30s

  # --------------------------------------------- SUPPLIER -------------------------------------------------------------

  supplier:
    image: ghcr.io/tobias-pe/supplier:latest
    env_file:
      - ./config/docker.env
    environment:
      - SERVICE_NAME=supplier
    depends_on:
      - rabbit-mq
    deploy:
      mode: replicated
      replicas: 4
      placement:
        max_replicas_per_node: 4
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
      restart_policy:
        delay: 5s
        window: 30s


    # ------------------------------------------- MONITORING -----------------------------------------------------------
  prometheus:
    image: ghcr.io/tobias-pe/prometheus-swarm:latest
    ports:
      - "9000:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=${PROMETHEUS_RETENTION:-24h}'
    volumes:
      - prometheus_data:/prometheus
    environment:
      - JOBS=api-gateway:50000 cart:9216 currency:9216 e-mail:9216 order:9216 payment:9216 shipment:9216 stock:9216 supplier:9216
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 30s
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 128M

  node-exporter:
    image: ghcr.io/tobias-pe/node-exporter:latest
    command:
      - '--path.sysfs=/host/sys'
      - '--path.procfs=/host/proc'
      - '--collector.textfile.directory=/etc/node-exporter/'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
      - '--no-collector.ipvs'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /etc/hostname:/etc/nodename
    environment:
      - NODE_ID={{.Node.ID}}
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 30s
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  dockerd-exporter:
    image: ghcr.io/tobias-pe/dockerd-nginx:latest
    environment:
      # linux: 172.17.0.1 ; windows: host.docker.internal
      - DOCKER_GWBRIDGE_IP=172.17.0.1
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 30s
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  cadvisor:
    image: raymondmm/cadvisor
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/rootfs:ro
      - /var/run:/var/run
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    command: -logtostderr -docker_only
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 30s
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 64M

  influxdb:
    image: influxdb:1.8
    deploy:
      mode: replicated
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 30s
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 64M

  grafana:
    image: grafana/grafana:8.2.6
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./config/grafana/dashboards:/etc/grafana/provisioning/dashboards/
      - ./config/grafana/dashboards:/etc/grafana/dashboards/
    deploy:
      mode: replicated
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 30s
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 64M

volumes:
  prometheus_data: { }
  grafana_data: { }