version: "3"

services:

  api-gateway:
    build:
      dockerfile: ./services/api-gateway/Dockerfile
    ports:
      - "50000:50000"
    env_file:
      - ./config/docker.env
    depends_on:
      - currency

  currency:
    env_file:
      - ./config/docker.env
    build:
      dockerfile: ./services/currency/Dockerfile
