name: Docker

on:
  schedule:
    - cron: '0 8 * * *' # every day at 8am UTC
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dockerfiles:
    name: Build and push ${{matrix.image}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: api-gateway
            path: ./services/api-gateway/Dockerfile
          - image: api-gateway-nginx
            path: ./docker/nginx/api-gateway/Dockerfile
          - image: currency
            path: ./services/currency/Dockerfile
          - image: currency-nginx
            path: ./docker/nginx/currency/Dockerfile
          - image: stock
            path: ./services/stock/Dockerfile
          - image: stock-nginx
            path: ./docker/nginx/stock/Dockerfile
          - image: mongo-seed
            path: ./docker/mongo/Dockerfile
          - image: cart
            path: ./services/cart/Dockerfile
          - image: cart-nginx
            path: ./docker/nginx/cart/Dockerfile
          - image: order
            path: ./services/order/Dockerfile
          - image: order-nginx
            path: ./docker/nginx/order/Dockerfile
          - image: payment
            path: ./services/payment/Dockerfile
          - image: shipment
            path: ./services/shipment/Dockerfile
          - image: email
            path: ./services/email/Dockerfile
          - image: supplier
            path: ./services/supplier/Dockerfile
          - image: prometheus
            path: ./docker/prometheus/Dockerfile
          - image: prometheus-swarm
            path: ./docker/prometheus-swarm/Dockerfile
          - image: node-exporter
            path: ./docker/node-exporter/Dockerfile
          - image: dockerd-nginx
            path: ./docker/nginx/dockerd/Dockerfile
          - image: locust
            path: ./docker/locust/Dockerfile

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: ${{ matrix.path }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/tobias-pe/${{ matrix.image }}:latest, ghcr.io/tobias-pe/${{ matrix.image }}:${{ github.run_id }}
          
      - name: Raise issue on failure
        if: failure()
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Dump context
        if: always()
        uses: crazy-max/ghaction-dump-context@v1
