name: Docker

on:
  schedule:
    - cron: '0 8 * * *' # every day at 8am UTC
  push:
  pull_request:

jobs:
  dockerfiles:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: api-gateway
            path: ./services/api-gateway/Dockerfile
          - image: api-gateway-nginx
            path: ./build/nginx/api-gateway/Dockerfile
          - image: currency
            path: ./services/currency/Dockerfile
          - image: currency-nginx
            path: ./build/nginx/currency/Dockerfile
          - image: stock
            path: ./services/stock/Dockerfile
          - image: stock-nginx
            path: ./build/nginx/stock/Dockerfile
          - image: mongo-seed
            path: ./build/mongo/Dockerfile
          - image: cart
            path: ./services/cart/Dockerfile
          - image: cart-nginx
            path: ./build/nginx/cart/Dockerfile
          - image: order
            path: ./services/order/Dockerfile
          - image: order-nginx
            path: ./build/nginx/order/Dockerfile
          - image: payment
            path: ./services/payment/Dockerfile
          - image: shipment
            path: ./services/shipment/Dockerfile
          - image: email
            path: ./services/email/Dockerfile

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build and push Docker image
        id: docker
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          dockerfile: ${{ matrix.path }}
          image: ${{ matrix.image }}
          tags: latest, ${{ github.run_id }}
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify Docker image
        run: |
          docker pull ${{ steps.docker.outputs.imageFullName }}:${{ github.run_id }}
          docker image inspect ${{ steps.docker.outputs.imageFullName }}:${{ github.run_id }}
      - name: Raise issue on failure
        if: failure()
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Dump context
        if: always()
        uses: crazy-max/ghaction-dump-context@v1